<?php
defined('BASEPATH') OR exit('No direct script access allowed');

class Sertifikat extends CI_Controller {
  public function __construct(){
    parent::__construct();
    date_default_timezone_set("Asia/Jakarta");

    $this->load->model(['M_sertifikat']);
    $this->load->library('mailer');
  }

  public function index(){
    $this->template->view('sertifikat');
  }

  public function data_sertifikat(){
    $this->template->view('data_sertifikat');

  }

  public function template(){
    $this->load->view('template');

  }

  public function send_sertifikat(){
    // GET DATA 
    $nama   = htmlspecialchars($this->input->post('NAMA'));
    $nrp    = htmlspecialchars($this->input->post('NRP'));
    $jenis  = htmlspecialchars($this->input->post('JENIS'));

    if ($jenis == 1) :
      $gambar = base_url()."assets/sertifikat_keaktifan_18.png";
    elseif($jenis == 2):
      $gambar = base_url()."assets/sertifikat_pengurus_18.png";
    elseif($jenis == 3):
      $gambar = base_url()."assets/sertifikat_keaktifan_19.png";
    endif;

    // CREATE GAMBAR
    $image  = imagecreatefrompng($gambar);
    $white  = imageColorAllocate($image, 255, 255, 255);
    $black  = imageColorAllocate($image, 0, 0, 0);

    $font   = "C:\Windows\Fonts\LHANDW.ttf"; 
    $size   = 82;
      //definisikan lebar gambar agar posisi teks selalu ditengah berapapun jumlah hurufnya
    $image_width  = imagesx($image);  
      //membuat textbox agar text centered
    $text_box     = imagettfbbox($size,0,$font,$nama);
    $text_width   = $text_box[2]-$text_box[0]; // lower right corner - lower left corner
    $text_height  = $text_box[3]-$text_box[1];

    $x            = ($image_width/2) - ($text_width/2);
    $y            = ($jenis == 1 ? 1550 : ($jenis == 2 ? 1600 : 1550));

    //generate sertifikat beserta namanya
    imagettftext($image, $size, 0, $x+100, $y, $black, $font, $nama);

    // INIT GAMBAR
    $jenis  = ($jenis == 1 ? "Keaktifan ANGGOTA HIC '18" : ($jenis == 2 ? "Pengurus HIC" : "Keaktifan ANGGOTA HIC '19"));

    ob_clean();

    //tampilkan di browser
    // header("Content-type:  image/png");
    
    // save image file

    // init file name
    $time       = time();
    $file_name  = "{$jenis}_{$nrp}_{$time}.png";
    imagepng($image, "./berkas/sertifikat/{$file_name}");
    
    // Send Image to Browser
    // imagepng($image);

    // Clear Memory
    imagedestroy($image);


    // SEND EMAIL
    $message = "<style type='text/css'>
    .box{
      background-color: #f6f6f6 !important;
      width: 100%;
      padding: 30px 0;
      font-family: sans-serif;
      font-size: 14px;
      vertical-align: top;
    }
    .box-content{
      background-color: #ffffff !important;
      width: 50%;
      margin: auto;
      padding: 20px;
      border-radius: 3px;
    }
    tr.content > td{
      padding-bottom: 10px;
      word-spacing: normal;
      line-height: 23px;
    }
    </style>
    <table border='0' cellpadding='0' cellspacing='0' class='box'>
    <tr>
    <td>
    <table border='0' cellpadding='0' cellspacing='0' class='box-content'>
    <tr class='content'>
    <td>Hai {$nama}, Berikut kami kirimkan E-Sertifikat {$jenis} anda dalam UKM HIC untuk dapat dipergunakan sebagaimana mestinya, Surat Keterangan dapat anda akses melalui QR Code yang telah tertera pada E-Sertifikat.</td>
    </tr>
    <tr class='content'>
    <td><hr><p>Terima Kasih,<br>Salam, HIC</p></td>
    </tr>
    </table>
    </td>
    </tr>
    </table>
    <hr>
    <small>This email is automatically generated by the system, please do not reply directly!!!</small>
    ";

    $mail = array(
      'to'        => $nrp."@mhs.stiki.ac.id",
      'subject'   => "Sertifikat {$jenis} - {$nrp} {$nama}",
      'message'   => $message,
      'file_name' => $file_name
    );

    if ($this->mailer->send($mail) == FALSE) {
      echo 'Message could not be sent. <br>';
      echo 'Mailer Error: ' . $mail->ErrorInfo;
      echo '<br>Contact ADMIN ';
      unlink("./berkas/sertifikat/{$file_name}");
      die();
    }else {
      $this->session->set_flashdata('success', "Berhasil mengirim sertifikat atas nama {$nama} - {$nrp}@mhs.stiki.ac.id !!");
      redirect(base_url());
    }

  }

}
